### ISSUE TITLE
Map does not render at full height

### ISSUE THREAD

**Issue by trytuna** [maplibre/ngx-maplibre-gl#114] opened 2023-10-20 11:34 UTC
Hello folks,

Embedding ngx-maplibre-gl in an Ionic project does show a bug with the rendering. Basically the bug is that the map isn't rendered at full height of the parent view. I've created a sample application to demonstrate it (link below).

Fortunately there is a hack that I can use to make it work:
https://github.com/trytuna/IonicMapLibre/blob/eddba061eafbe96214a3595048585a315a2deb95/src/app/map/map.page.ts#L21

You can see the bug in action if you comment out line 21.

```
git clone https://github.com/trytuna/IonicMapLibre
cd IonicMapLibre
npm install
./node_modules/.bin/ionic serve
```

Maybe we can somehow figure out where the problem exactly is. If the conclusion is that there is a bug in Ionic I am happy to open an Issue there.

**Comment by HarelM** [comment] 2023-10-20 11:46
I guess it's a css issue - the map will take the 100% height, but at the time of the map creation this size is 0, and maybe the resize event isn't being called.
Did you try other ways to set the map container size: i.e. `top: 0; bottom: 0` or `height: 100vh`.
I would consider looking in that direction.

**Comment by HarelM** [comment] 2023-10-20 11:47
I have the following angular app, and I don't need to do any hack to have it full screen:
https://github.com/IsraelHikingMap/Site/blob/645b0544889446f35de97a0fb30a89c60ec9c4aa/IsraelHiking.Web/src/application/components/map/main-map.component.html#L6

**Comment by trytuna** [comment] 2023-10-20 14:06
I've tried `top: 0; bottom: 0;` and `height: 100vh;` that does not make any differences. If its an CSS issue then it shouldn't be possible to fix it with the hack I guess.

I've noticed that if you reload `http://localhost:8100/home/map` multiple times that at some point the map renders at full height. So it seems that there is a race condition somewhere.

**Comment by tbo47** [comment] 2023-11-03 06:21
I installed and run `https://github.com/trytuna/IonicMapLibre` and it works fine for me. It takes 100% of the height. 

On firefox and Chrome.

```
➜  IonicMapLibre git:(main) npm ls @maplibre/ngx-maplibre-gl
IonicMapLibre@0.0.1 /home/user/p/IonicMapLibre
└── @maplibre/ngx-maplibre-gl@16.0.0
```

**Comment by trytuna** [comment] 2023-11-05 09:42
> I installed and run `https://github.com/trytuna/IonicMapLibre` and it works fine for me. It takes 100% of the height.
> 
> On firefox and Chrome.
> 
> ```
> ➜  IonicMapLibre git:(main) npm ls @maplibre/ngx-maplibre-gl
> IonicMapLibre@0.0.1 /home/user/p/IonicMapLibre
> └── @maplibre/ngx-maplibre-gl@16.0.0
> ```

Have you disabled the hack?

**Comment by tbo47** [comment] 2023-11-05 12:32
oh, I see. No I haven't

**Comment by HarelM** [comment] 2024-02-09 20:17
Feel free to open a PR if you find a solution or root cause.
Closing this issue for now as I don't know how to proceed with this issue.

**Closed by HarelM** 2024-02-09 20:17 UTC
