### ISSUE TITLE
Browser window resizing brakes map rendering

### ISSUE THREAD

**Issue by trytuna** [maplibre/ngx-maplibre-gl#99] opened 2023-05-24 13:29 UTC
As mentioned in https://github.com/maplibre/ngx-maplibre-gl/pull/97 there is a weird bug that brakes the map rendering if the browser window gets resized. Here is a sample project https://stackblitz.com/edit/angular-bbrhvd

This issue could be worked around by setting a fixed height for the `mgl-map`-Tag. I have a feeling that many people are going to run into this problem. Its best to address this issue somehow I guess.

```
mgl-map {
  height: 400px;
}
```

I did screen recordings to show what actually happens

**Safari Version 16.4 (18615.1.26.11.23)**

https://github.com/maplibre/ngx-maplibre-gl/assets/128096/0b5310a7-1dca-4e9b-a942-675bec72be59

**Chrome Version 113.0.5672.92 (Official Build) (arm64)**

https://github.com/maplibre/ngx-maplibre-gl/assets/128096/5133a088-d6ec-4b5a-a1d6-640bdbc610c3

**Comment by HarelM** [comment] 2023-05-24 13:41
Thanks for taking the time to open this issue!
Can you see if you can reproduce this with plain JavaScript, without ngx-maplibre wrapper?

**Comment by HarelM** [comment] 2023-05-24 14:05
I see some references to resize in this code base, they probably assume some things about how it used to work as opposed to how it is working in version 3 of maplibre due to resize observer changes.
Feel free to try and play with the code here to fix this.
If you have an easy way to reproduce this on the showcase here we can create a test from it and solve this faster.

**Comment by trytuna** [comment] 2023-05-24 14:27
As I am trying to do a demo in plain javascript I was not able to reproduce it with my initial code anymore... I am trying to grasp my brain around that for a day or two. I going to keep this issue up to date

**Comment by HarelM** [comment] 2023-05-24 17:11
Looking at the initial video I think the css of maplibre was missing, and this might create some weird stuff.
I'll keep this issue open, but I can't reproduce with the current link in this issue.
Please close this issue if can't reproduce.

**Closed** 2023-05-25 06:54 UTC

**Comment by HarelM** [comment] 2023-05-25 07:12
No worries :-)
