### ISSUE TITLE
v15 breaks popups with [closeOnClick]="true"

### ISSUE THREAD

**Issue by hheexx** [maplibre/ngx-maplibre-gl#100] opened 2023-06-23 10:33 UTC
After v15 update popups are broken on out website.

I will do more debugging in 1-2 weeks timeframe, just wanted to mention it here now in case more people have a problem.

It's not underlaying maplibre problem, we migrated to v3 without problems.

**Comment by HarelM** [comment] 2023-06-23 12:35
I haven't seen any issues with popups, but it might be that my use case isn't as complicated.
Let me know if you need need anything.

**Comment by hheexx** [comment] 2023-06-26 19:25
Additional Info:

Problem only happens with [closeOnClick]="true". If I set it to false popup starts working.

**Comment by HarelM** [comment] 2023-06-26 19:27
Can you reproduce this in the showcase project?
It should allow testing it in E2E and also reduce a lot of noise hopefully.

**Comment by hheexx** [comment] 2023-07-05 18:08
I have started but it's not gonna be easy because our map is interconnected with lot of stuff.
This update is not top priority for us so I'm not sure when will I have time to finish.

I can provide link to our dev environment so you can see error if that helps at all.

**Comment by HarelM** [comment] 2023-07-05 19:08
Naaa... I need a minimal reproduction...

**Comment by tzetter** [comment] 2023-08-01 08:11
Hard to say without any information on what "broken" in this context means, but the mention of `closeOnClick` makes me think that it could be related to the changes in my PR https://github.com/maplibre/ngx-maplibre-gl/pull/87 

Is the issue that a popup (not linked to a marker) disappears when the map is clicked? In that case you should note that this is the expected behavior when `closeOnClick` is set to `true`. This wasn't the case in previous versions as popups always were recreated when any input changed.

**Comment by HarelM** [comment] 2023-08-01 08:47
I just realized that the changelog is not even remotely up to date :-(
But yes, #87 was added as part of version 15.
@hheexx you can try reverting this PR in the latest version, use `patch-package` and see if it solves your issue.

**Comment by HarelM** [comment] 2023-08-01 09:18
I've updated the changelog with relevant PRs. Seems that version 15 was about a year in the making, so it has more changes compared to other versions. Having said that, there's not a lot of changes in total, so reverting each change shouldn't be hard to pinpoint the issue, assuming it is in the code here and not in Angular.

**Comment by hheexx** [comment] 2023-08-01 23:17
Yea, I have just backtracked and it's caused by #87

**Comment by hheexx** [comment] 2023-08-01 23:24
Here is the code:

We have mgl-popup in code with ng-contaner inside so we can load in angular components.

on pin click we first fly to pin:
```
let zoom = this.map.getZoom();
    if (this.map.getZoom() < 13) {
      zoom = 13;
    }

    this.popupPropertyCard.location = cords;

    var propDataReq = this.http.get(`/api/propertyView/${propId}`).toPromise();
    this.map.flyTo(
      { center: cords, speed: 0.7, curve: 2, offset: [0, 150], zoom: zoom },
      { propRequest: propDataReq }
    );
```


then on (moveEnd) event we create component and put it in ng-container:

```
 private async createPropertyPopup(propRequest: Promise<object>) {
    let popupEl = this.popupPropertyCardRef.createComponent(PropertyCardComponent, {
      injector: this.injector,
    });

    let prop: any = await propRequest;

    popupEl.instance.customClass = 'property-card--serp property-card--serp-map';
    popupEl.instance.property = prop;
    popupEl.instance.selectedIndex = 0;

    this.popupPropertyCard.component = popupEl;

    popupEl.changeDetectorRef.detectChanges();
    this.cdr.detectChanges();
  }
```




After merge of #87 when I click on a pin flyTo happens and createPropertyPopup is called from moveEnd event but no popup is shown.

**Comment by tzetter** [comment] 2023-08-02 05:41
I looked at the code above, but it didn't really help me understand the issue you're having. Is the issue that popups disappear when you click the map for the second time or are you never seeing any popups?

**Comment by HarelM** [comment] 2023-08-02 06:24
@hheexx since you better understand problem now, can you please try and create a small reproduction using stackblitz?

**Comment by HarelM** [comment] 2023-08-02 11:18
@hheexx let's try and focus more on facts and less on speculations.
The code in #87 looks legit, if it introduced a bug lets uncover it and fix it.
Without a reproduction of the issue the only person that can push this forward is you, everything else is speculations...

**Comment by hheexx** [comment] 2023-08-02 16:07
At this moment it's probably easier for me to find fix then to make reproduction.
I will look into it and maybe ask some questions.....

**Comment by hheexx** [comment] 2023-08-03 11:35
What I believe is happening is that our popup is visible from page load with cordinates [0,0] and empty content.
On click we put component content inside of popup and change it's location to right place.

Before #87 popup was recreated when we change cordinates so it got the right size from content inside.
After #87 popup is not recreated on location change so it stays 0 size.

I have fixed our code not to reuse and move same popup but to create new one dynamically. Now it works.
But new code is pretty big and ugly for a simple and common use case of angular component inside popup:


```
let pcEl = this.mapContainerRef.createComponent(PropertyCardComponent, {
      injector: this.injector,
    });

    let popupEl = this.mapContainerRef.createComponent(PopupComponent, {
      injector: this.mapContainerRef.injector,
      projectableNodes: [[pcEl.location.nativeElement]],
    });

    popupEl.instance.lngLat = cords;
    popupEl.instance.className = 'prop-popup';
    popupEl.instance.offset = 25;
    popupEl.instance.closeButton = false;
    popupEl.instance.maxWidth = '288px';

    this.popupPropertyCardRef = popupEl;
``` 



I have feature Idea that PopupComponent should accept TemplateRef as Input. That would make this scenario lot easier.

**Comment by tzetter** [comment] 2023-08-03 12:30
Based on that it sounds like the problem was as I initially expected, meaning that it initially was created and opened an empty popup at the coordinates 0, 0 and then was closed when you clicked the map at the new location.

This is in my opinion the intended behavior for a popup with `closeOnClick` set to true. The same things will happen if you do the same thing without ngx-maplibre-gl.

```typescript
const myPopup = new Popup({closeOnClick: true}).setLngLat([0, 0]);
map.on('click', ev => myPopup.setLngLat(ev.lngLat))
```

My recommendation for you would be to set `closeOnClick` to `false` and then to use other mechanisms for closing the popup, like in the showcase example https://github.com/maplibre/ngx-maplibre-gl/blob/main/projects/showcase/src/app/demo/examples/polygon-popup-on-click.component.ts

You should also note that intializing the lnglat as 0, 0 probably isn't a good idea. You shouldn't create the popup component (or your property card component for that matter) using an injector, as that kind of defeats the purpose of using the library at all. I would either just do it all in the template using something like:

```typescript
<mgl-popup
    *ngIf="thing"
    [lngLat]="thing.lngLat"
    [closeOnClick]="false"
>
    <app-property-card [thing]="thing"></app-property-card>
</mgl-popup>
```

or alternatively just use maplibre-gl directly and create normal popups.

This all kind goes outside the scope of this issue, but hope it was of some help.

**Comment by HarelM** [comment] 2023-08-04 05:42
@tzetter thanks a lot for this detailed answer!
@hheexx can I close this issue then?

**Comment by hheexx** [comment] 2023-08-04 14:29
Yea, 

thanks for help!

**Closed** 2023-08-04 14:31 UTC
