### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by Sampath-Lokuge** [maplibre/ngx-maplibre-gl#89] opened 2023-03-27 07:30 UTC
Hi,

Is this support for `Angular 15+`? i.e. I can see Angular 14 only yet. Your thoughts? Thanks!

**Comment by HarelM** [comment] 2023-03-27 11:43
I haven't got around to upgrading my project to angular 15 due to the support drop of flexbox.
I hope this does supports Angular 15 without any modifications, but if not, it might be better to wait a bit for the release of maplibre 3.x and then create a new version, or split that and first support maplibre 3 and then update angular to 15.
Generally speaking, yes, this library should support angular 15 (and probably 16)...
Feel free to open a PR if this is something you can easily do, I could update the PR once stuff are updated if needed...

**Comment by Sampath-Lokuge** [comment] 2023-03-27 12:37
Ok sure. I'm still working on the Angular 14 app. So I'll continue with Angular 14 until my client will tell me to upgrade it to 15 or 16. I hope at that time your library also will have version 3. Thanks for your feedback!

**Comment by n0daft** [comment] 2023-04-05 12:19
Hi @HarelM 

We currently have our own little ngx-wrapper of maplibre (ng 15, without ng Flex-Layout but pure CSS flexbox) which offers a few components and some opinionated functionality. We are rather quick to update our libraries to the newest angular versions.

I'm currently evaluating the usage of this library as base for our wrapper. I actually just added this library and tried if it would work with some early success.

Could you elaborate a little about the roadmap? You mention maplibre 3. Is there a major release of maplibre-gl-js planned? Also you mention Angulars' drop out of Flex-Layout. However I don't really see any usages of FxLayout within the library. 

We migrated all our ng projects to use pure CSS flexbox.
Thanks for elaborating.

**Comment by HarelM** [comment] 2023-04-05 13:28
I'm working towards a release of maplibre 3, I hope it will be released in a month or so.
Since there are breaking changes there I think it will be better to release this package only afterwards.
I'm also not sure if the current release doesn't support angular 15 as I haven't upgraded my own project (not related to maplibre) to try.
But, as mentioned before, I'm open to PRs 😀

**Comment by tomLadder** [comment] 2023-04-15 12:50
Just wanted to let you know, that i'm also working with Angular 15 and did not face any issues yet with this library :)

**Comment by rokozeit** [comment] 2023-04-20 14:03
Hi,

I am on rather a newbie to angular and ngx-maplibre-gl. I am on Angular 15. I created a new project and followed the steps from the readme. The moment I am importing NgxMapLibreGLModule into app.module.ts I am getting a bunch of error messages starting with: 


`Error: node_modules/@maplibre/ngx-maplibre-gl/lib/layer/layer.component.d.ts:2:10 - error TS2614: Module '"maplibre-gl"' has no exported member 'LayerSpecification'. Did you mean to use 'import LayerSpecification from "maplibre-gl"' instead?`

Same for `'FilterSpecification'`.
Additionally there are errors like:

```
Error: node_modules/@maplibre/ngx-maplibre-gl/lib/layer/layer.component.d.ts:23:5 - error TS2416: Property 'layerClick' in type 'LayerComponent' is not assignable to the same property in base type 'LayerEvents'.
  Type 'EventEmitter<MapMouseEvent & { features?: Feature<Geometry, GeoJsonProperties>[] | undefined; } & EventData>' is not assignable to type 'EventEmitter<MapMouseEvent & { features?: MapGeoJSONFeature[] | undefined; } & EventData>'.
    Types of property 'subscribe' are incompatible.
      Type '{ (next?: ((value: MapMouseEvent & { features?: Feature<Geometry, GeoJsonProperties>[] | undefined; } & EventData) => void) | undefined, error?: ((error: any) => void) | undefined, complete?: (() => void) | undefined): Subscription; (observerOrNext?: any, error?: any, complete?: any): Subscription; }' is not assignable to type '{ (next?: ((value: MapMouseEvent & { features?: MapGeoJSONFeature[] | undefined; } & EventData) => void) | undefined, error?: ((error: any) => void) | undefined, complete?: (() => void) | undefined): Subscription; (observerOrNext?: any, error?: any, complete?: any): Subscription; }'.
        Types of parameters 'next' and 'next' are incompatible.
          Types of parameters 'value' and 'value' are incompatible.
            Type 'MapMouseEvent & { features?: Feature<Geometry, GeoJsonProperties>[] | undefined; } & EventData' is not assignable to type 'MapMouseEvent & { features?: MapGeoJSONFeature[] | undefined; } & EventData'.
```
Since others seam not to have issues on Angular 15, I guess it is on my side. Anyone some idea? OS is Win 11 Pro.

Here some details on my side:

```
Angular CLI: 15.0.5
Node: 18.15.0
Package Manager: npm 9.5.0
OS: win32 ia32

Angular: 15.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.6
@angular-devkit/build-angular   15.2.6
@angular-devkit/core            15.2.6
@angular-devkit/schematics      15.0.5
@angular/cli                    15.0.5
@schematics/angular             15.0.5
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by HarelM** [comment] 2023-04-20 14:32
Which version of maplibre are you using?

**Comment by VictorNorman** [comment] 2023-04-28 19:38
I am having similar problems to @rokozeit . But, I'm trying to build a mobile app using Ionic over Angular.

Here is my info:

```Ionic:

   Ionic CLI                     : 7.0.1 (/Users/vtn2/Library/pnpm/global/5/.pnpm/@ionic+cli@7.0.1/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.4
   @angular-devkit/build-angular : 15.2.7
   @angular-devkit/schematics    : 15.2.7
   @angular/cli                  : 15.2.7
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.8.0
   @capacitor/android : not installed
   @capacitor/core    : 4.8.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.19.1 (/Users/vtn2/.nvm/versions/node/v16.19.1/bin/node)
   npm    : 9.5.0
   OS     : macOS
```

And here is my package.json:

```
{
  "name": "trees",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^15.0.0",
    "@angular/core": "^15.0.0",
    "@angular/forms": "^15.0.0",
    "@angular/platform-browser": "^15.0.0",
    "@angular/platform-browser-dynamic": "^15.0.0",
    "@angular/router": "^15.0.0",
    "@capacitor/app": "4.1.1",
    "@capacitor/core": "4.8.0",
    "@capacitor/haptics": "4.1.0",
    "@capacitor/keyboard": "4.1.1",
    "@capacitor/status-bar": "4.1.1",
    "@ionic/angular": "^7.0.0",
    "@maplibre/ngx-maplibre-gl": "^14.0.0-pre.2",
    "ionicons": "^7.0.0",
    "maplibre-gl": "^3.0.0-pre.5",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.0.0",
    "@angular-eslint/builder": "^15.0.0",
    "@angular-eslint/eslint-plugin": "^15.0.0",
    "@angular-eslint/eslint-plugin-template": "^15.0.0",
    "@angular-eslint/schematics": "^15.0.0",
    "@angular-eslint/template-parser": "^15.0.0",
    "@angular/cli": "^15.0.0",
    "@angular/compiler": "^15.0.0",
    "@angular/compiler-cli": "^15.0.0",
    "@angular/language-service": "^15.0.0",
    "@capacitor/cli": "4.8.0",
    "@ionic/angular-toolkit": "^9.0.0",
    "@types/jasmine": "~4.0.0",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "5.3.0",
    "@typescript-eslint/parser": "5.3.0",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~4.3.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.8.4"
  },
  "description": "An Ionic project"
}
```

My repo is here: [https://github.com/VictorNorman/calvin-trees](https://github.com/VictorNorman/calvin-trees)

**Comment by HarelM** [comment] 2023-04-28 19:52
In maplibre-gl 3.0.0-pre.5 there is a problems with the types.
I recently created a fix to solve this, but I would avoid using that version ATM, there are also other issues with latest version that needs this library to be fixed accordingly.
For now use 3.0.0-pre.3 with this library as I think they will work.
Or you can use a non-pre-release version, I think those work with angular 15 as well.
I hope version 3 will be released soon so I can create a proper release to this library as well...

**Comment by VictorNorman** [comment] 2023-04-29 14:52
Here is my package.json that does build with Ionic 7 and Angular 15:

```
{
  "name": "trees",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^15.0.0",
    "@angular/core": "^15.0.0",
    "@angular/forms": "^15.0.0",
    "@angular/platform-browser": "^15.0.0",
    "@angular/platform-browser-dynamic": "^15.0.0",
    "@angular/router": "^15.0.0",
    "@capacitor/app": "4.1.1",
    "@capacitor/core": "4.8.0",
    "@capacitor/haptics": "4.1.0",
    "@capacitor/keyboard": "4.1.1",
    "@capacitor/status-bar": "4.1.1",
    "@ionic/angular": "^7.0.0",
    "@maplibre/ngx-maplibre-gl": "13.0.0",
    "ionicons": "^7.0.0",
    "maplibre-gl": "2.4.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.0.0",
    "@angular-eslint/builder": "^15.0.0",
    "@angular-eslint/eslint-plugin": "^15.0.0",
    "@angular-eslint/eslint-plugin-template": "^15.0.0",
    "@angular-eslint/schematics": "^15.0.0",
    "@angular-eslint/template-parser": "^15.0.0",
    "@angular/cli": "^15.0.0",
    "@angular/compiler": "^15.0.0",
    "@angular/compiler-cli": "^15.0.0",
    "@angular/language-service": "^15.0.0",
    "@capacitor/cli": "4.8.0",
    "@ionic/angular-toolkit": "^9.0.0",
    "@types/jasmine": "~4.0.0",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "5.3.0",
    "@typescript-eslint/parser": "5.3.0",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~4.3.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.8.4"
  },
  "description": "An Ionic project"
}

```

**Comment by HarelM** [comment] 2023-04-29 17:32
Yup, that would work too - the stable versions.

**Comment by rokozeit** [comment] 2023-05-01 11:16
Changing from maplibre-gl 3.0.0-pre.5 to maplibre-gl 3.0.0-pre.3 did the magic for me.

Thanks.

**Comment by HarelM** [comment] 2023-05-01 11:22
I'll keep this issue open and close it when angular 15 support and maplibre 3 are released, but generally speaking, this library works with angular 15 already.

**Comment by trytuna** [comment] 2023-05-17 11:13
I just ran into the exact same problem. Luckily I figured that out by myself but boy - that took a long time. Hope that gets fixed soon

**Comment by trytuna** [comment] 2023-05-18 21:09
Thank you for caring and your help but I'm still getting this error. This could be fixed bu setting `strictNullChecks: false` in `tsconfig.json` but that shouldn't be necessary.

```
Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:1145:2 - error TS2416: Property 'getDefault' in type 'BindVertexArray' is not assignable to the same property in base type 'BaseValue<WebGLVertexArrayObject>'.
  Type '() => WebGLVertexArrayObject | null' is not assignable to type '() => WebGLVertexArrayObject'.
    Type 'WebGLVertexArrayObject | null' is not assignable to type 'WebGLVertexArrayObject'.
      Type 'null' is not assignable to type 'WebGLVertexArrayObject'.

1145  getDefault(): WebGLVertexArrayObject | null;
```

**Comment by HarelM** [comment] 2023-05-18 21:36
We replaced webgl1 with 2, the above code and error is not part of this library, right?

**Comment by trytuna** [comment] 2023-05-18 21:43
Yep, its an issue in maplibre-gl-js. I guess this line is the issuehttps://github.com/maplibre/maplibre-gl-js/blob/013ce4b73ead072dd9aaf82acaab3a4c3249a90a/src/gl/value.ts#L48
It should be `getDefault(): T | null`

**Comment by HarelM** [comment] 2023-05-23 19:36
@n0daft regarding the roadmap of this project/wrapper:
I don't have anything concrete.
It's basically a thin wrapper over maplibre-gl with some fixes to common pitfalls (removing a source while it is used by a layer etc) and a good way to declare things.
I try to make sure it is following the Angular releases and that it uses the latest maplibre-gl.
I'm very open to PRs and would love other to help out maintaining it.
If there are setting that you see that are available in maplibre and not available here, or there are features that can be introduced here that are related to the Angular lifecycle (ngChanges etc) feel free to open a PR.

**Comment by rokozeit** [comment] 2023-05-24 11:12
Hi I am on 16. Works like a charm. But due to the error reported by @trytuna I am on `mapslibre 3.0.0-pre.3`.


```
 "private": true,
  "dependencies": {
    "@angular/animations": "^16.0.0",
    "@angular/cdk": "^16.0.0",
    "@angular/common": "^16.0.0",
    "@angular/compiler": "^16.0.0",
    "@angular/core": "^16.0.0",
    "@angular/flex-layout": "^15.0.0-beta.42",
    "@angular/forms": "^16.0.0",
    "@angular/material": "^16.0.0",
    "@angular/platform-browser": "^16.0.0",
    "@angular/platform-browser-dynamic": "^16.0.0",
    "@angular/router": "^16.0.0",
    "@fortawesome/angular-fontawesome": "^0.13.0",
    "@fortawesome/fontawesome-svg-core": "^6.2.1",
    "@fortawesome/free-brands-svg-icons": "^6.2.1",
    "@fortawesome/free-regular-svg-icons": "^6.2.1",
    "@fortawesome/free-solid-svg-icons": "^6.2.1",
    "@maplibre/ngx-maplibre-gl": "^14.0.0-pre.3",
    "@tmcw/togeojson": "^5.6.1",
    "@turf/turf": "^6.5.0",
    "crypto-js": "^4.1.1",
    "get-google-fonts": "^1.2.2",
    "maplibre-gl": "3.0.0-pre.3",
    "material-design-icons": "^3.0.1",
    "ng-gallery": "^8.0.4",
    "ngx-colors": "^3.5.2",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "uuid": "^9.0.0",
    "webdav": "^5.0.0-r3",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.0.0",
    "@angular/cli": "~16.0.0",
    "@angular/compiler-cli": "^16.0.0",
    "@types/crypto-js": "^4.1.1",
    "@types/jasmine": "~4.3.0",
    "@types/leaflet": "^1.9.0",
    "@types/uuid": "^9.0.1",
    "dotenv": "^16.0.3",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "^4.9.3",
    "yargs": "^17.7.2"
  }
```

**Comment by rokozeit** [comment] 2023-05-24 11:59
Just tired updating to `"maplibre-gl": "^3.0.0"` and `@maplibre/ngx-maplibre-gl": "^14.0.0-pre.4"`. Still on angular 16. Getting the following errors:

```
Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:1145:2 - error TS2416: Property 'getDefault' in type 'BindVertexArray' is not assignable to the same property in base type 'BaseValue<WebGLVertexArrayObject>'.
  Type '() => WebGLVertexArrayObject | null' is not assignable to type '() => WebGLVertexArrayObject'.
    Type 'WebGLVertexArrayObject | null' is not assignable to type 'WebGLVertexArrayObject'.
      Type 'null' is not assignable to type 'WebGLVertexArrayObject'.

1145  getDefault(): WebGLVertexArrayObject | null;
      ~~~~~~~~~~


Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:11075:1 - error TS1383: Only named exports may use 'export type'.

11075 export type * from "@maplibre/maplibre-gl-style-spec";
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: src/app/components/maplibre-map/maplibre-map.component.ts:117:11 - error TS2345: Argument of type 'Position' is not assignable to parameter of type '[number, number, number, number] | LngLatLike | [LngLatLike, LngLatLike] | undefined'.
  Type 'number[]' is not assignable to type '[LngLatLike, LngLatLike]'.
    Target requires 2 element(s) but source may have fewer.

117           lineString.coordinates[0],
```

**Comment by HarelM** [comment] 2023-05-24 12:01
I'll start with integrating it in my project.
Worst case I'll publish a new version with the relevant fixes.

**Closed** 2023-05-24 12:49 UTC
Labels: enhancement

**Comment by HarelM** [comment] 2023-05-24 12:50
Not saying there isn't an issue here, but the original issue was about Angular 15.
Feel free to open a new issue and clearly describe the problem.
If the problem is with maplibre-gl-js I would recommend opening an issue there, or better yet a PR :-)

**Comment by HarelM** [comment] 2023-05-24 17:35
I've updated the readme to include this.
There're currently exported types which are exported using Typescript 5 syntax so Angular 15 and typescript 4 are failing (`export type * from "@maplibre/maplibre-gl-style-spec"`).
In order to resolve both there's a need to add the following compiler options to tsconfig:
```
"compilerOptions": {
    ...
    "strictNullChecks": false,
    "skipLibCheck": true,
}
```
